version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: ratesdb:dev
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: ratesapi:dev
    ports:
     - "3000:3000"
    depends_on:
    - "db"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=db
