version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: ratesdb:dev
    ports:
     - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: ratesapi:dev
    ports:
     - "3000:3000"
    depends_on:
    - "db"
